### ISSUE TITLE
cspyce build fails on MacOS

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-cspyce#169]
It appears the GitHub MacOS runner has updated their C compiler and it is now throwing fatal errors while compiling cspyce.

**Comment by fyellin** [comment]
Just to give an explanation of what's happening. 

Since 1999, C has supposedly not accepted an implicit "int".  From Wikipedia:

> In particular, a declaration that lacks a type specifier no longer has int implicitly assumed. The C standards committee decided that it was of more value for compilers to diagnose inadvertent omission of the type specifier than to silently process legacy code that relied on implicit int. In practice, compilers are likely to display a warning, then assume int and continue translating the program.

For unknown reasons, stom NAIF code still uses these implicit ints, even though they should have been gone 25 years ago. For example, the file `fmt.c` still has:

```
 static
#ifdef KR_headers
op_gen(a,b,c,d)
#else
op_gen(int a, int b, int c, int d)
#endif
```

I'm not quite sure what the right way to fix this is.  It is possible that future versions of Clang will support -Wimplicit-int again.   Should we patch the code ourselves? Should we convince NAIF to add `int` to all the places that it's missing.

**Comment by rfrenchseti** [comment]
I think we should definitely let Boris know this is happening. Would you be willing to write up the problem and send it to him?
